baseURL = 'https://themagitian.github.io/'
languageCode = 'en-us'
paginatePath = "page"
showMenuItems = 0
theme = "terminal"
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  themeColor = "red"
  # fullWidthTheme = true
  centerTheme = true
  
[params.logo]
   logoText = "Magitian's blog"
   logoHomeLink = "/"
